name: bachatbazaar
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.9.7 
  firebase_auth: ^0.8.2  
  http: ^0.12.0+1
  shimmer: ^1.0.0
  cached_network_image: ^0.5.1
  image_picker: ^0.5.0+9
  firebase_storage: ^2.1.0+1
  paytm: ^0.0.2
  webview_flutter: ^0.3.5+2 
  date_format: ^1.0.6
  font_awesome_flutter: ^8.4.0
  flare_flutter: ^1.3.4
  flutter_sparkline: ^0.1.0
  charts_flutter: ^0.6.0
  flutter_webview_plugin: 
  flutter_custom_tabs: "^0.6.0"
  progress_hud: ^1.1.0
  modal_progress_hud: ^0.1.3
  cupertino_icons: ^0.1.2
  material_search: ^0.2.8
  flutter_upi: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/cart.png
  - assets/cart1.png
  - assets/cart2.png
  - assets/BachatBazaarLogoAnimation.flr
  - assets/MyLoading.flr
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Title
      fonts:
        - asset: fonts/Title.ttf
    - family: Subtitle
      fonts:
        - asset: fonts/Subtitle.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
